//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public byte[] tratamiento { get; set; }
        public decimal monto { get; set; }
        public bool borrado { get; set; }
        public long medicold { get; set; }
        public long ingresoId { get; set; }
    
        public virtual Ingreso Ingreso { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
